<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>
<?php if ($_attributeValue) :?>
    <?php if($_code === 'arbour'):?>

        <?php
        switch ($_attributeValue){
            case "Multi-Fit Arbor":
                echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('multi-fit')
                    ->toHtml();
                break;
            case 'Porter Cable Original':
                echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('Porter_cable')
                    ->toHtml();
                break;
            case 'New Porter Cable / Quick Release Arbor':
                echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('Quick_release')
                    ->toHtml();
                break;
            case 'Classic Rockwell Arbor':
                echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('classic_rock')
                    ->toHtml();
                break;
            case 'Supercut Arbor':
                echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('Super_cut')
                    ->toHtml();
                break;
            default:
                break;
        }
        ?>
        <style>
            .compat-tab .column {
                width: 30%;
                float: left;
                margin-right: 3%;
            }
            .compat-tab .column ul li:nth-child(odd) {
                background: #f6f6f6;
            }
        </style>
    <?php else :?>
        <div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
            <?php if ($renderLabel) :?>
                <strong class="type"><?= $block->escapeHtml($_attributeLabel) ?></strong>
            <?php endif; ?>
            <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue ?></div>
        </div>
    <?php endif; ?>
<?php endif; ?>
